let isUserLoggerIn = false   // ...............Executar um codigo  somente se o usuário não estiver logado....
if(!isUserLoggerIn){
  console.log("...Você precisa fazer o login para continuar...   ):  ")
}
console.log(!true)  // ..............Algo que não é verdadeiro é falso....................................
console.log(!false)//........................... E algo que não é falso é verdadeiro...............